name: Descargar hojas de cálculo

on:
  schedule:
    - cron: '0 8 */2 * *'  # Cada 2 días a las 08:00 UTC
  workflow_dispatch:       # También puedes ejecutarlo manualmente

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script de descarga
        run: python descargar_hojas.py

      - name: Hacer commit y push
        run: |
          git config user.name "jsgaston"
          git config user.email "jsgastoniriartecabrera@gmail.com"
          git add .
          git commit -m "Actualización automática de hojas de cálculo"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
