name: Descargar hojas de cálculo y actualizar repo

on:
  schedule:
    - cron: '0 6 */2 * *'  # Cada 2 días a las 06:00 UTC
  workflow_dispatch:       # También lo puedes ejecutar manualmente

jobs:
  actualizar:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script de descarga
        run: python descargar_hojas.py
